### ISSUE TITLE
Update included certificate bundle

### ISSUE THREAD

**Issue by nateberkopec** [certifi/ruby-certifi#1]
It seems to be as easy as [curling down a new one](https://github.com/certifi/python-certifi/blob/master/tasks.py). Is this correct?

**Comment by Lukasa** [comment]
It is, but we've changed our download location for the other packages to `mkcert.org`. I'll aim to do this today.

**Comment by nateberkopec** [comment]
Do you want to throw together a Rake task to do this? If you can give me some description on how you'd like it to work, I can open a PR.

**Comment by Lukasa** [comment]
I'd certainly be happy to have that. Basically the intention is just to curl down https://mkcert.org/generate/, and chuck the output into cacert.pem.

**Comment by Lukasa** [comment]
Ugh, wrong button. ;)

**Comment by Lukasa** [comment]
Done in #2.
