### ISSUE TITLE
Permissions to upload new gems

### ISSUE THREAD

**Issue by Lukasa** [certifi/ruby-certifi#3]
I don't have permission to upload a new version of the gem. @hone?

**Comment by n10v** [comment]
https://github.com/kennethreitz should have these permissions

**Comment by hone** [comment]
yeah, i don't have permissions sadly :(

**Comment by Lukasa** [comment]
Ah, rough. Paging @kennethreitz!

**Comment by hone** [comment]
:) he's on vacation this week juts FYI.

**Comment by Lukasa** [comment]
I have magic Kenneth summoning powers. I believe this should be fixed now, I'll try uploading a new version of the gem. =D

**Comment by Lukasa** [comment]
\o/ New version uploaded, should be available shortly.

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:
